INSERT INTO agents (
  id,
  slug,
  agent_address,
  display_name,
  owner_name,
  owner_domain,
  owner_country,
  purpose,
  description,
  capabilities_json,
  supported_intents_json,
  autonomy_level,
  inbox_mode,
  inbox_url,
  data_policy,
  contact_policy,
  trust_badges_json,
  status,
  public_key,
  created_at,
  updated_at
) VALUES
(
  'agt_currency_rates',
  'currency-rates-agent',
  'currency-rates-agent@sthali.com',
  'Currency Rates Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Returns informational currency exchange rates from public market data for structured agent requests.',
  'Sthali-managed read-only API wrapper over Frankfurter public exchange-rate data. Send get_exchange_rate with from, to, and optional amount.',
  '["get_exchange_rate","convert_currency","public_market_data"]',
  '[{"intent":"get_exchange_rate","requires_approval":false,"max_response_time_seconds":30},{"intent":"convert_currency","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public currency-market data only. Do not send sensitive personal data. Responses are informational and not financial advice.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_public_holidays',
  'holiday-calendar-agent',
  'holiday-calendar-agent@sthali.com',
  'Holiday Calendar Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Returns public holiday calendars for country and year requests.',
  'Sthali-managed read-only API wrapper over Nager.Date public holiday data. Send get_public_holidays with country_code and optional year.',
  '["get_public_holidays","check_business_day_context","public_calendar_data"]',
  '[{"intent":"get_public_holidays","requires_approval":false,"max_response_time_seconds":30},{"intent":"check_business_day_context","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public calendar data only. Confirm with local authorities before making operational commitments.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_weather_risk',
  'weather-risk-agent',
  'weather-risk-agent@sthali.com',
  'Weather Risk Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Returns current weather and short forecast context for city or coordinate requests.',
  'Sthali-managed read-only API wrapper over Open-Meteo public forecast data. Send get_weather_forecast with city or latitude and longitude.',
  '["get_weather_forecast","check_weather_risk","public_weather_data"]',
  '[{"intent":"get_weather_forecast","requires_approval":false,"max_response_time_seconds":30},{"intent":"check_weather_risk","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public weather data only. Do not use as the only source for safety-critical decisions.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
)
ON CONFLICT(id) DO UPDATE SET
  slug = excluded.slug,
  agent_address = excluded.agent_address,
  display_name = excluded.display_name,
  owner_name = excluded.owner_name,
  owner_domain = excluded.owner_domain,
  owner_country = excluded.owner_country,
  purpose = excluded.purpose,
  description = excluded.description,
  capabilities_json = excluded.capabilities_json,
  supported_intents_json = excluded.supported_intents_json,
  autonomy_level = excluded.autonomy_level,
  inbox_mode = excluded.inbox_mode,
  inbox_url = excluded.inbox_url,
  data_policy = excluded.data_policy,
  contact_policy = excluded.contact_policy,
  trust_badges_json = excluded.trust_badges_json,
  status = excluded.status,
  public_key = excluded.public_key,
  updated_at = excluded.updated_at;
