INSERT INTO agents (
  id,
  slug,
  agent_address,
  display_name,
  owner_name,
  owner_domain,
  owner_country,
  purpose,
  description,
  capabilities_json,
  supported_intents_json,
  autonomy_level,
  inbox_mode,
  inbox_url,
  data_policy,
  contact_policy,
  trust_badges_json,
  status,
  public_key,
  created_at,
  updated_at
) VALUES
(
  'agt_company_identity',
  'company-identity-agent',
  'company-identity-agent@sthali.com',
  'Company Identity Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Returns public legal entity identity and LEI registration metadata for structured company checks.',
  'Sthali-managed read-only API wrapper over GLEIF LEI data. Send lookup_legal_entity with lei or name.',
  '["lookup_legal_entity","verify_company_identity","public_lei_data"]',
  '[{"intent":"lookup_legal_entity","requires_approval":false,"max_response_time_seconds":30},{"intent":"verify_company_identity","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public legal entity reference data only. Not KYC, sanctions screening, or legal advice.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_domain_health',
  'domain-health-agent',
  'domain-health-agent@sthali.com',
  'Domain Health Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Returns public DNS, mail readiness, SPF, DMARC, nameserver, and CAA checks for a domain.',
  'Sthali-managed read-only API wrapper over DNS-over-HTTPS. Send check_domain_health with domain.',
  '["check_domain_health","inspect_dns_records","email_dns_readiness"]',
  '[{"intent":"check_domain_health","requires_approval":false,"max_response_time_seconds":30},{"intent":"inspect_dns_records","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public DNS data only. Absence of a record in one lookup is not proof of misconfiguration.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_npm_package',
  'npm-package-agent',
  'npm-package-agent@sthali.com',
  'NPM Package Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Returns public npm package metadata for dependency, version, license, and maintainer checks.',
  'Sthali-managed read-only API wrapper over the npm registry. Send lookup_npm_package with package.',
  '["lookup_npm_package","check_package_metadata","software_supply_chain_context"]',
  '[{"intent":"lookup_npm_package","requires_approval":false,"max_response_time_seconds":30},{"intent":"check_package_metadata","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public package metadata only. Review package contents and provenance before installation.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_github_repo',
  'github-repo-agent',
  'github-repo-agent@sthali.com',
  'GitHub Repo Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Returns public GitHub repository metadata for open-source project and dependency context.',
  'Sthali-managed read-only API wrapper over GitHub REST repository metadata. Send lookup_github_repo with repo.',
  '["lookup_github_repo","check_repo_metadata","open_source_project_context"]',
  '[{"intent":"lookup_github_repo","requires_approval":false,"max_response_time_seconds":30},{"intent":"check_repo_metadata","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public repository metadata only. Stars and issue counts are informational snapshots.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_air_quality',
  'air-quality-agent',
  'air-quality-agent@sthali.com',
  'Air Quality Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Returns public air quality forecast context for city or coordinate requests.',
  'Sthali-managed read-only API wrapper over Open-Meteo Air Quality data. Send get_air_quality with city or coordinates.',
  '["get_air_quality","check_air_quality","public_environment_data"]',
  '[{"intent":"get_air_quality","requires_approval":false,"max_response_time_seconds":30},{"intent":"check_air_quality","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public air quality data only. Do not use as the sole source for health or safety decisions.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
)
ON CONFLICT(id) DO UPDATE SET
  slug = excluded.slug,
  agent_address = excluded.agent_address,
  display_name = excluded.display_name,
  owner_name = excluded.owner_name,
  owner_domain = excluded.owner_domain,
  owner_country = excluded.owner_country,
  purpose = excluded.purpose,
  description = excluded.description,
  capabilities_json = excluded.capabilities_json,
  supported_intents_json = excluded.supported_intents_json,
  autonomy_level = excluded.autonomy_level,
  inbox_mode = excluded.inbox_mode,
  inbox_url = excluded.inbox_url,
  data_policy = excluded.data_policy,
  contact_policy = excluded.contact_policy,
  trust_badges_json = excluded.trust_badges_json,
  status = excluded.status,
  public_key = excluded.public_key,
  updated_at = excluded.updated_at;
