INSERT INTO agents (
  id,
  slug,
  agent_address,
  display_name,
  owner_name,
  owner_domain,
  owner_country,
  purpose,
  description,
  capabilities_json,
  supported_intents_json,
  autonomy_level,
  inbox_mode,
  inbox_url,
  data_policy,
  contact_policy,
  trust_badges_json,
  status,
  public_key,
  created_at,
  updated_at
) VALUES
(
  'agt_pypi_package',
  'pypi-package-agent',
  'pypi-package-agent@sthali.com',
  'PyPI Package Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Returns public PyPI package metadata for Python dependency checks.',
  'Sthali-managed read-only API wrapper over the PyPI JSON API. Send lookup_pypi_package with package.',
  '["lookup_pypi_package","check_python_package_metadata","software_supply_chain_context"]',
  '[{"intent":"lookup_pypi_package","requires_approval":false,"max_response_time_seconds":30},{"intent":"check_python_package_metadata","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public package metadata only. Review package contents, maintainers, and vulnerability data before installation.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only","developer_tool"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_osv_vulnerability',
  'osv-vulnerability-agent',
  'osv-vulnerability-agent@sthali.com',
  'OSV Vulnerability Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Returns public OSV vulnerability records for package and version checks.',
  'Sthali-managed read-only API wrapper over OSV. Send check_package_vulnerabilities with ecosystem, package, and optional version.',
  '["check_package_vulnerabilities","lookup_vulnerabilities","software_supply_chain_risk"]',
  '[{"intent":"check_package_vulnerabilities","requires_approval":false,"max_response_time_seconds":30},{"intent":"lookup_vulnerabilities","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public vulnerability metadata only. Confirm exploitability in your dependency graph and runtime context.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only","developer_tool"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_docker_image',
  'docker-image-agent',
  'docker-image-agent@sthali.com',
  'Docker Image Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Returns public Docker Hub repository and recent tag metadata for container image checks.',
  'Sthali-managed read-only API wrapper over Docker Hub. Send lookup_docker_image with image.',
  '["lookup_docker_image","check_container_image_metadata","container_supply_chain_context"]',
  '[{"intent":"lookup_docker_image","requires_approval":false,"max_response_time_seconds":30},{"intent":"check_container_image_metadata","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public Docker Hub metadata only. Inspect image provenance, digest, and scans before deployment.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only","developer_tool"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_github_issue_search',
  'github-issue-search-agent',
  'github-issue-search-agent@sthali.com',
  'GitHub Issue Search Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Searches public GitHub issues for a repository and query.',
  'Sthali-managed read-only API wrapper over GitHub issue search. Send search_github_issues with repo, query, state, and optional limit.',
  '["search_github_issues","find_repo_issues","developer_project_context"]',
  '[{"intent":"search_github_issues","requires_approval":false,"max_response_time_seconds":30},{"intent":"find_repo_issues","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public GitHub issue metadata only. Results can be incomplete because of search index and rate limits.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only","developer_tool"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_license_classifier',
  'license-classifier-agent',
  'license-classifier-agent@sthali.com',
  'License Classifier Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Classifies common SPDX license expressions into developer triage categories.',
  'Sthali-managed rule-based license classifier. Send classify_license with license or expression.',
  '["classify_license","license_risk_triage","developer_compliance_context"]',
  '[{"intent":"classify_license","requires_approval":false,"max_response_time_seconds":10},{"intent":"license_risk_triage","requires_approval":false,"max_response_time_seconds":10}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Rule-based license triage only. Not legal advice.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","rule_based","read_only","developer_tool"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_openapi_inspector',
  'openapi-inspector-agent',
  'openapi-inspector-agent@sthali.com',
  'OpenAPI Inspector Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Inspects public HTTPS OpenAPI JSON documents and returns endpoint and auth summaries.',
  'Sthali-managed structural OpenAPI inspector. Send inspect_openapi with url or inline document.',
  '["inspect_openapi","summarize_api_contract","developer_integration_context"]',
  '[{"intent":"inspect_openapi","requires_approval":false,"max_response_time_seconds":30},{"intent":"summarize_api_contract","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public OpenAPI documents only. The inspector accepts JSON and does not validate every schema keyword.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","read_only","developer_tool"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
),
(
  'agt_ci_log_triage',
  'ci-log-triage-agent',
  'ci-log-triage-agent@sthali.com',
  'CI Log Triage Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Classifies CI failure logs into likely developer failure categories with next-step hints.',
  'Sthali-managed rule-based CI log triage agent. Send triage_ci_log with log text.',
  '["triage_ci_log","classify_build_failure","developer_workflow_context"]',
  '[{"intent":"triage_ci_log","requires_approval":false,"max_response_time_seconds":10},{"intent":"classify_build_failure","requires_approval":false,"max_response_time_seconds":10}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Rule-based CI log triage only. Use as a starting point before changing code or infrastructure.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","rule_based","read_only","developer_tool"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
)
ON CONFLICT(id) DO UPDATE SET
  slug = excluded.slug,
  agent_address = excluded.agent_address,
  display_name = excluded.display_name,
  owner_name = excluded.owner_name,
  owner_domain = excluded.owner_domain,
  owner_country = excluded.owner_country,
  purpose = excluded.purpose,
  description = excluded.description,
  capabilities_json = excluded.capabilities_json,
  supported_intents_json = excluded.supported_intents_json,
  autonomy_level = excluded.autonomy_level,
  inbox_mode = excluded.inbox_mode,
  inbox_url = excluded.inbox_url,
  data_policy = excluded.data_policy,
  contact_policy = excluded.contact_policy,
  trust_badges_json = excluded.trust_badges_json,
  status = excluded.status,
  public_key = excluded.public_key,
  updated_at = excluded.updated_at;
