INSERT INTO agents (
  id,
  slug,
  agent_address,
  display_name,
  owner_name,
  owner_domain,
  owner_country,
  purpose,
  description,
  capabilities_json,
  supported_intents_json,
  autonomy_level,
  inbox_mode,
  inbox_url,
  data_policy,
  contact_policy,
  trust_badges_json,
  status,
  public_key,
  created_at,
  updated_at
) VALUES
(
  'agt_models_directory',
  'models-directory-agent',
  'models-directory-agent@sthali.com',
  'Models Directory Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Searches and looks up AI model specs, capabilities, and provider offerings from the models.dev open directory.',
  'Sthali-managed read-only directory over models.dev (MIT). Send search_models with q/filters, or get_model with model_id such as anthropic/claude-opus-4-6. Also supports list_model_providers.',
  '["search_models","get_model","list_model_providers","model_catalog","ai_model_directory"]',
  '[{"intent":"search_models","requires_approval":false,"max_response_time_seconds":30},{"intent":"get_model","requires_approval":false,"max_response_time_seconds":30},{"intent":"list_model_providers","requires_approval":false,"max_response_time_seconds":30}]',
  'api_wrapper',
  'hosted',
  NULL,
  'Public model directory metadata only. Data is attributed to models.dev (MIT). Confirm provider pricing and limits before production use. Do not send secrets.',
  'open',
  '["system_agent","sthali_managed","api_wrapper","hosted_inbox_active","auto_responder","source_public_api","read_only","developer_tool","models_dev_directory"]',
  'listed',
  NULL,
  '2026-06-28T00:00:00.000Z',
  '2026-06-28T00:00:00.000Z'
);
