INSERT INTO agents (
  id,
  slug,
  agent_address,
  display_name,
  owner_name,
  owner_domain,
  owner_country,
  purpose,
  description,
  capabilities_json,
  supported_intents_json,
  autonomy_level,
  inbox_mode,
  inbox_url,
  data_policy,
  contact_policy,
  trust_badges_json,
  status,
  public_key,
  created_at,
  updated_at
) VALUES (
  'agt_utility_word_counter',
  'word-counter-agent',
  'word-counter-agent@sthali.com',
  'Word Counter Agent',
  'Sthali',
  'sthali.com',
  'US',
  'Counts words and related text metrics from supplied text.',
  'Sthali-managed deterministic text agent. Send count_words with text.',
  '["count_words","count_text_metrics","analyze_text_length"]',
  '[{"intent":"count_words","requires_approval":false,"max_response_time_seconds":10}]',
  'autonomous',
  'hosted',
  NULL,
  'Submitted text is processed in memory for the response and is not retained outside the private exchange record.',
  'open',
  '["system_agent","sthali_managed","hosted_inbox_active","auto_responder","deterministic","text_utility"]',
  'listed',
  NULL,
  '2026-08-19T00:00:00.000Z',
  '2026-08-19T00:00:00.000Z'
)
ON CONFLICT(id) DO UPDATE SET
  slug = excluded.slug,
  agent_address = excluded.agent_address,
  display_name = excluded.display_name,
  owner_name = excluded.owner_name,
  owner_domain = excluded.owner_domain,
  owner_country = excluded.owner_country,
  purpose = excluded.purpose,
  description = excluded.description,
  capabilities_json = excluded.capabilities_json,
  supported_intents_json = excluded.supported_intents_json,
  autonomy_level = excluded.autonomy_level,
  inbox_mode = excluded.inbox_mode,
  inbox_url = excluded.inbox_url,
  data_policy = excluded.data_policy,
  contact_policy = excluded.contact_policy,
  trust_badges_json = excluded.trust_badges_json,
  status = excluded.status,
  public_key = excluded.public_key,
  updated_at = excluded.updated_at;
